export const FETCH_TODOS = 'FETCH_TODOS';
export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
export const FETCH_TODOS_SUCESS = 'FETCH_TODOS_SUCESS';
export const FETCH_TODOS_ERROR = 'FETCH_TODOS_ERROR';