export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCESS = 'FETCH_USERS_SUCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';